# Project: 8.≈≈–ÚÀ„∑®
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 1.≤Â»Î≈≈–Ú.o
LINKOBJ  = 1.≤Â»Î≈≈–Ú.o
LIBS     = -L"E:/professionalstudy/Dev-Cpp/MinGW64/lib" -L"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 8.≈≈–ÚÀ„∑®.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c99
CFLAGS   = $(INCS) -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

1.≤Â»Î≈≈–Ú.o: 1.≤Â»Î≈≈–Ú.cpp
	$(CPP) -c 1.≤Â»Î≈≈–Ú.cpp -o 1.≤Â»Î≈≈–Ú.o $(CXXFLAGS)
