# Project: 6.图
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 4.2图的单源点最短路径-有向带权图-Dijkstra.o
LINKOBJ  = 4.2图的单源点最短路径-有向带权图-Dijkstra.o
LIBS     = -L"E:/professionalstudy/Dev-Cpp/MinGW64/lib" -L"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 6.图.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c99
CFLAGS   = $(INCS) -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

4.2图的单源点最短路径-有向带权图-Dijkstra.o: 4.2图的单源点最短路径-有向带权图-Dijkstra.cpp
	$(CPP) -c 4.2图的单源点最短路径-有向带权图-Dijkstra.cpp -o 4.2图的单源点最短路径-有向带权图-Dijkstra.o $(CXXFLAGS)
