# Project: 3.栈和队列
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 7.1栈的应用-表达式求值-后缀表达式的计算.o
LINKOBJ  = 7.1栈的应用-表达式求值-后缀表达式的计算.o
LIBS     = -L"E:/professionalstudy/Dev-Cpp/MinGW64/lib" -L"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/professionalstudy/Dev-Cpp/MinGW64/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/professionalstudy/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 3.栈和队列.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c99
CFLAGS   = $(INCS) -g3 -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

7.1栈的应用-表达式求值-后缀表达式的计算.o: 7.1栈的应用-表达式求值-后缀表达式的计算.cpp
	$(CPP) -c 7.1栈的应用-表达式求值-后缀表达式的计算.cpp -o 7.1栈的应用-表达式求值-后缀表达式的计算.o $(CXXFLAGS)
